-- 코드를 입력하세요
SELECT LEFT(CREATED_AT, 4) as YEAR, MID(CREATED_AT, 6, 2) as MONTH, 
    SUM(CATEGORY) as  CANCEL_COUNT,
    ABS(SUM(
        CASE WHEN CATEGORY = 0 THEN 0
        ELSE AMOUNT 
        END)) as AMOUNT
FROM CARD_USAGES
GROUP BY YEAR , MONTH 
ORDER BY YEAR DESC , MONTH DESC