-- 코드를 입력하세요
SELECT S.ID, S.NAME, T.c as `노선 수`
FROM SUBWAY_STATIONS S
JOIN (SELECT COUNT(LINE_COLOR) as c, STATION_ID
    FROM LINE_ROUTES
    GROUP BY STATION_ID HAVING c != 0) T
ON S.ID = T.STATION_ID
ORDER BY S.ID

